# Generated by Django 5.2.1 on 2025-05-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_codigo_confirmacao_usuario_senha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('codigo', models.CharField(max_length=6)),
                ('dados', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
