# Generated by Django 5.2.1 on 2025-06-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_codigoconfirmacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
