# Generated by Django 5.2 on 2025-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.TextField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
