# Generated by Django 5.2 on 2025-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filme_ano_filme_descricao_filme_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
