# Generated by Django 5.2.1 on 2025-05-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('diretor', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('nota_media', models.FloatField(default=0.0)),
                ('numero_avaliacoes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('nome', 'diretor', 'ano')},
            },
        ),
    ]
