# Generated by Django 5.2.1 on 2025-05-15 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='sentimento_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme'),
        ),
    ]
